# Permalinks
permalink:           pretty

# Setup
title:               Sobit Akhmedov
description:         >
                     Sobit Akhmedov is a backend/infrastructure/scalability specialist with sufficient background in
                     managing high load production stacks. Currently lives in Berlin, Germany and works at GetYourGuide.
tagline:             Software Engineer
url:                 http://sobit.me
paginate:            3
baseurl:             ""
excerpt_separator:   <!--more-->
analytics_id:        UA-74071333-1

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Sobit Akhmedov
  url:               http://sobit.me/
  email:             sobit.akhmedov@gmail.com
  twitter:           dront7

# Custom vars
version:             2.0.0

# Atom feed
feed:
  path:              atom.xml

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
