baseURL = "https://sobit.me/"
languageCode = "en-us"
title = "Sobit Akhmedov"
theme = "lanyon"
disqusShortname = "sobit"
googleAnalytics = "UA-74071333-1"

[permalinks]
  posts = "/:year/:month/:day/:title/"

[params]
  title = "Sobit Akhmedov"
  tagline = "Staff Software Engineer"
  description = "Sobit Akhmedov is a staff software engineer with 14 years experience building e-commerce, financial and cloud storage solutions for startup and Big Five companies."

[markup]
  [markup.highlight]
    style = "tango"
  [markup.goldmark.renderer]
    unsafe = true
